export const urls = {
  USER_SIGNUP: "auth/user/signup",
  USER_LOGIN: "auth/user/login",
  AGENT_SIGNUP: "agent/signup",
  AGENT_LOGIN: "agent/login",
  AGENT_ADD_CATEGORY: "agent/category-add",
  ADMIN_LOGIN: "admin/login",
  ADMIN_GET_ALL_USERS: "admin/get-all-users",
  ADMIN_GET_ALL_AGENTS: "admin/get-all-agents",
  ADMIN_BLOCK_USER: "admin/block-user/",
  ADMIN_BLOCK_AGENT: "admin/block-agent/",
  ADMIN_GET_ALL_UNVERIFIED_AGENTS: "admin/get-all-unverified-agents",
  ADMIN_VERIFY_AGENTS: "admin/agent-verification/",
  AGENT_GET_ALL_CATEGORY: "agent/get-all-category/",
  AGENT_DELETE_CATEGORY: "agent/delete-category",
  AGENT_ADD_PACKAGE: "agent/add-tour-package",
  AGENT_GET_ALL_PACKAGES: "agent/get-all-package/",
  USER_GET_ALL_PACKAGES: "auth/get-tour-packages",
  AGENT_DISABLE_PACKAGE: "agent/disable-package/",
  AGENT_GET_PACKAGE: "agent/get-package/",
  AGENT_UPDATE_PACKAGE: "agent/update-package/",
  AGENT_DELETE_PACKAGE: "agent/delete-package/",
  USER_GET_PACKAGE: "auth/package-details/",
  USER_BOOK_PACKAGE: "auth/book-package",
  USER_LOGIN_WITH_GOOGLE: "auth/login-with-google",
  USER_GET_USER_DETAILS: "auth/user-profile",
  USER_UPDATE_PROFILE: "auth/user-profile-update",
  USER_GET_TOUR_BOOKED_DETAILS: "auth/user-get-package-booked-data/",
  USER_GET_ALL_BOOKING: "auth/user-get-all-bookings",
  USER_PAYMENT_STATUS_CHANGE: "auth/user-Pay-status-change",
  AGENT_GET_ALL_BOOKING: "agent/get-all-booking",
  AGENT_VERIFICATION_CHECK: "agent/isVerified",
  AGENT_GET_PROFILE: "agent/get-profile",
  AGENT_UPDATE_PROFILE: "agent/agent-profile-update",
  USER_GET_ALERT_MESSAGES: "auth/user-get-alert-messages",
  AGENT_CREATE_ALERT_MESSAGE: "agent/alert-message",
  USER_CREATE_COMMUNITY: "auth/user-create-community",
  USER_GET_ALL_COMMUNITIES: "auth/get-all-community",
  USER_JOIN_COMMUNITY: "auth/join-community",
  USER_GET_ALL_JOINED_AND_NOT_JOINED_COMMUNITY:
    "auth/getAlluserJoinedAndNotJoinedcommunity",
  USER_CREATE_CONVERSATION: "auth/create-conversation",
  USER_GET_ALL_CONVERSATION_COMMUNITY: "auth/get-all-coversation/",
  ADMIN_GET_BASIC_DETAILS_USER_AGENT_PACKAGE:
    "admin/get-basic-details-user-agent",
  ADMIN_GET_AGENTS_STATUS: "admin/get-all-agents-status",
  ADMIN_GET_BOOKING_STAT: "admin/get-all-booking-stat",
  AGENT_GET_ALL_BOOKING_STAT: "agent/get-all-bookingStat",
  USER_GET_ALL_UNIQUE_CATEGORIES: "auth/get-all-unique-category",
  ADMIN_GET_REVENUE: "admin/get-revenu",
  AGENT_GET_REVENUE: "agent/get-agent-revenue",
  AGENT_GET_USERCOUNT_BOOKINGCOUNT: "agent/get-userCount-successBookingCount",
  USER_UPDATE_PASSWORD: "auth/user-password-update",
  USER_REQUEST_OTP: "auth/user-generate-otp",
  USER_VERIFY_OTP: "auth/verify-otp",
  USER_UPDATE_PASSWORD_WITH_EMAIL: "auth/user-password-update-withEmail",
};

const BASE_URL = "https://voyago.site/api/";
export const SOCKET_URL = "wss://voyago.site/socket.io/";
//  const BASE_URL= 'http://localhost:8000/api/';
// export const SOCKET_URL = "ws://localhost:8000";
export default BASE_URL;
